pipeline{
    agent none
    stages{
        stage('Backend'){
            agent {
                docker (image 'maven:3.8.1-adoptopenjdk-11')
            }
            steps{
                sh 'mvn --version'
            }
        }
        
        stage('Frontend'){
            agent{
                docker (image 'node:latest')
            }
            steps{
                sh 'node --version'
            }
        }
    }
}
